language: perl

matrics:
  include:
  - perl: '5.10'
    dist: trusty
  - perl: '5.12'
    dist: trusty
  - perl: '5.14'
  - perl: '5.16'
  - perl: '5.18'
  - perl: '5.20'
  - perl: '5.22'
  - perl: '5.24'
  - perl: '5.26'
  - perl: '5.28'
  - perl: '5.30'
  - perl: '5.32'
  - perl: '5.34'

notifications:
  email: false
  slack:
    secure: kdwF5ADLEwI6dEm31bvkcke3C5eJ9Xgeo9pW2r7uGxu5YqNfEpikEseTpOzM4W82vlDvnMwIvRgx8/iULFNg+NOsinR9Jk6W99pZwbf3CkxTqY23sVMAkAvpUSB1L+F45nXb2GqNtyCkKnp0ITsltus4OT3inuIh7rMhzgALL8X9Qv2cFbcnGyVQnmdZJwrvs4lB0IqavpgTPOmrgmojaSI01TffVSugddl/2N3vmjX6Z6QDLNcojuOKhEwrCvAQrK22BxXDW0k6KJAuH58iy6GQdOcVRLpeRpWupCODPWnpo9yYpN+KVvl1hQ9konvGAhP6b6vU3vxkWoU1oNuFfrqd6voqKjddoi9XWoOjjW6t5pSA8HfxqZkBepJKpiz/cEqnElGJ35HNhlhQzIkpenOgwnGFyrYHG3Ib7aBwbnVbia8OfBDsG4Z+bcGQyMF4waRqdYBt2DZ7EleOBfAoWKRsQ2dKaZBgzAVe/qjqiuuM6N2eAIfX45n1eR05Ez3pygphFc+sLcykzbfpUYVaC77cNjUGQLo5BfyseNqLkq5A7qPFdwzSSvJwB1Sw3LQhTwcijQ8vpsC3Fvgqyqg9JmvGMboXcK2tXmAzFdtj3J+4pQYWFfPKC1kU8RaqvzQd49+a8XFV+TdFlx3mXHwC2bf1IeaDzkUBE2umjEYUc0Y=