language: perl

matrics:
  include:
  - perl: '5.10'
    dist: trusty
  - perl: '5.12'
    dist: trusty
  - perl: '5.14'
  - perl: '5.16'
  - perl: '5.18'
  - perl: '5.20'
  - perl: '5.22'
  - perl: '5.24'
  - perl: '5.26'
  - perl: '5.28'
  - perl: '5.30'
  - perl: '5.32'
  - perl: '5.34'

notifications:
  email: false
  slack:
    secure: P1xM9GGbNc7+JojiZkEmi+VsSgxdUEsLme4HtiNUvcVkA8Dhb/sHqpfDYpZDI8KElTVg8wboTJoylzb3ioQ8YNF9G52McOJqzjIdJYoHPrSDuSZtRsyT+KmHW2LG/KV4WOUz2CV8a/oLxEdq1v001bevYrptRdITw42uTkSMcnYKrSKskiyghHeL546Amy2bSWioJi0uzX86ox6bhmDusgjQdpWbHIeSdeMRU4c8aPFs7St6KAIgpaNYR9E8hB6i35opQLnRxVrtuC7EAsHZ3hWGH4nYhH9wSTJqiuIbMGYsX3QseLnT2gzkMokQqqHvEzVd5Rj2i69tici799n7ngTTXKlMiy7zDb5QnkndzvuYMif9wJ4shFdTqtKaqboq8xpcStuMxkUtyv/oSwUhGL2eanCCB4CvyLUr32hEmfw7bHFCWqC077s51KJDX90cdsS5AJlyaDNWGCcvJDQLKnar2P4Fft2thDwxlubz3TaYmk97+J43dlWP4UYHkLFtjlcILaEOZlHC2hjlbgTWsdL5T4oamvD+Sjd7ZWc1SjvokicLlHC8qZKV5hdIiJlqZWZzWlSTX9JlmKXXfkZ5rqHuzDbsS4W2ADl4j9XdWfNW/wfext+8Nb3CTppLHYQdkYtQvl7JBNKc/+fiipsU8XCBvPSLfikQNOtsz3anZk4=
